services:
  pg_llm_db:
    build: .
    container_name: pg_llm_db
    environment:
      POSTGRES_USER: ${DB_POSTGRES:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: olist_db
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data:/tmp/olist_data
      - ./init_olist.sql:/docker-entrypoint-initdb.d/01-init-olist.sql
      - .:/pg_extension
    command: ["postgres", "-c", "shared_preload_libraries=vector"]

volumes:
  pg_data:
